### ISSUE TITLE
I am not able to setup project and run corenlp

### ISSUE THREAD

**Issue by srnsrn120** [Yale-LILY/LoFT#1]
Hi Team,
Thank you for this work, please help me to setup corenlp. i am not able to proceed

**Comment by yilunzhao** [comment]
Hi,

Thanks for your interest in our work! To install CoreNLP, could you please check out [this tutorial](https://stanfordnlp.github.io/CoreNLP/download.html)? 

If you are still having trouble setting up the environment for the `LoFT_data_processing` model, we also provide the already processed data in the [Google Drive/LoFT/LoFT_data_processing](https://drive.google.com/drive/folders/1W9c9pVPDnvdyqAMObwG3uzMJpeM68eUX?usp=sharing). You can directly save them in the same path as `LoFT_data_processing/file_structure.txt` shows, and turn to the second module `LoFT_framework`.
